"""update user table

Revision ID: 956818a4a339
Revises: 0e52dcd41fe3
Create Date: 2026-03-07 04:00:47.317267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '956818a4a339'
down_revision: Union[str, Sequence[str], None] = '0e52dcd41fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=200), nullable=True))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'birth')
    # ### end Alembic commands ###
